### ISSUE TITLE
HTTP 422: Unprocessable entity on registration.

### ISSUE THREAD

**Issue by typicalMoves** [akif2543/disarray#14]
Can't register. On mac too. 11.0.1

**Comment by akif2543** [comment]
Hi @typicalMoves. Sorry for the very delayed response. Could you give me some more context on this so I can try to reproduce it? What you entered and some logs would be helpful.

**Comment by typicalMoves** [comment]
Well now I'm getting this, as I had to download the source again etc and build it:
`user@MacBook-Air disarray % bundle exec rails db:seed
rails aborted!
LoadError: Unable to autoload constant ActiveStorage::Blob::Analyzable, expected /Library/Ruby/Gems/2.6.0/gems/activestorage-5.2.5/app/models/active_storage/blob/analyzable.rb to define it`

storage.yml
`test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>`
`local:
  service: Disk
  root: <%= Rails.root.join("storage") %>`

development.rb
`config.active_storage.service = :test`

**Comment by akif2543** [comment]
Found the culprit! It was the `credentials.yml.enc` file and some leftover references to my personal config. I created a new branch called `clone` where I removed all of these, so you should pull that to your local master and try again. I also updated the `README` to reflect this. Let me know how it goes.

**Comment by typicalMoves** [comment]
Works like a charm now. Will work on tinkering with it :p

Also my Rails and bundler was kinda bugged too so yeah
