### ISSUE TITLE
With install

### ISSUE THREAD

**Issue by Tajeeomstvo** [akif2543/disarray#26]
I got the npm install down but the ruby is what im having truble with! please help me?

**Comment by akif2543** [comment]
Hello,

I'm going to need some more context. Did you have a problem running `bundle install`? If so, do you have [bundler](https://bundler.io/)?

**Comment by Tajeeomstvo** [comment]
I don’t, I will need to install that! Thank you, I will be back if I need
help again!

**Comment by Tajeeomstvo** [comment]
i did the install command for it then ran bundle install and it gave me this erorr 
![image](https://user-images.githubusercontent.com/82711008/115117148-22da9700-9f6b-11eb-8445-e72e6aa75122.png)

**Comment by Tajeeomstvo** [comment]
If i dont mind asking? is there a way we can go in a discord call so it would be easy? i hope im not asking for to much

**Comment by Tajeeomstvo** [comment]
I have been tryng to get the install done but have not got any were?

**Comment by akif2543** [comment]
This is a problem with your computer's environment and does not have to do with this project so I'm closing this issue. You should be able to solve it by following [these instructions](https://bundler.io/blog/2019/05/14/solutions-for-cant-find-gem-bundler-with-executable-bundle.html). (Pro-tip: always Google your error messages first!)
