### ISSUE TITLE
Bundel seed command problem

### ISSUE THREAD

**Issue by Tajeeomstvo** [akif2543/disarray#27]
Hello, When i run the following command i get an error (bundle exec rails db:seed)

Error (WARNING: could not load hiredis extension, using (slower) pure Ruby implementation.
  Please add the following to your Gemfile to avoid polling for changes:
    gem 'wdm', '>= 0.1.0' if Gem.win_platform?
  Please add the following to your Gemfile to avoid polling for changes:
    gem 'wdm', '>= 0.1.0' if Gem.win_platform?
rails aborted!
LoadError: Unable to autoload constant ActiveStorage::Blob::Analyzable, expected C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/activestorage-5.2.5/app/models/active_storage/blob/analyzable.rb to define it
C:/Users/urewr/Desktop/disarray-master/app/models/user.rb:144:in `ensure_avatar'
C:/Users/urewr/Desktop/disarray-master/db/seeds.rb:4:in `<top (required)>'
bin/rails:9:in `<main>'
Tasks: TOP => db:seed)

**Comment by Tajeeomstvo** [comment]
I did google but i could not find anything?

**Comment by akif2543** [comment]
Hi, can you try the accepted answer here: https://stackoverflow.com/questions/32723710/add-line-of-code-to-gemfile-that-already-contains-that-line-of-code and let me know if that resolves it

**Comment by Tajeeomstvo** [comment]
Hello, It worked but now it says this error:

LoadError - Unable to autoload constant ActiveStorage::Blob::Analyzable, expected C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/activestorage-5.2.5/app/models/active_storage/blob/analyzable.rb to define it:
  app/models/user.rb:144:in `ensure_avatar'
  app/controllers/api/users_controller.rb:18:in `create'

**Comment by akif2543** [comment]
Make sure you pull from the `clone` branch and follow the instructions in the `README` about that and that should resolve it
