### ISSUE TITLE
there is a way to create a bot

### ISSUE THREAD

**Issue by werewolf26** [akif2543/disarray#29]
try to set up a bot but do not know where to start?

**Comment by akif2543** [comment]
What kind of bot are you thinking? If it's a chat bot, it would probably be better to do it in Python, but it is possible with Ruby or JavaScript. As to where to start, I'm not too sure either. I suppose it depends on how complicated you want to make it. For just some basic functionality you could totally build it into the Rails backend where ActionCable is [implemented](https://github.com/akif2543/disarray/blob/master/app/channels/chat_channel.rb#L13). Have it parse messages for commands and then broadcast responses accordingly

**Comment by werewolf26** [comment]
> What kind of bot are you thinking? If it's a chat bot, it would probably be better to do it in Python, but it is possible with Ruby or JavaScript. As to where to start, I'm not too sure either. I suppose it depends on how complicated you want to make it. For just some basic functionality you could totally build it into the Rails backend where ActionCable is [implemented](https://github.com/akif2543/disarray/blob/master/app/channels/chat_channel.rb#L13). Have it parse messages for commands and then broadcast responses accordingly

will I was thinking about making a way to like an api server or backend so people can create a bot with the email and password too like a chatbot or another thing for chatbot

**Comment by werewolf26** [comment]
and if use the python for like a chat bot when how to I setup for it

**Comment by MitchellHarrison** [comment]
I saw you starred my repo, but in case you need an example bot and you didn't see it, I have a bot class and a command class, put together into a chat bot that works well. The three files you'll need to read are [here](https://github.com/MitchellHarrison/mitchs-twitch-bot/blob/main/bot.py) for the bot class, [here](https://github.com/MitchellHarrison/mitchs-twitch-bot/blob/main/command.py) for the command class, and [here](https://github.com/MitchellHarrison/mitchs-twitch-bot/blob/main/chat_bot.py) for the chat bot script that I run to start it up. If you need credentials, you can check the [demo credentials file](https://github.com/MitchellHarrison/mitchs-twitch-bot/blob/main/credentials.env) to see where to put your credentials.

I hope this helps, and thanks for the star. ❤️

**Comment by werewolf26** [comment]
> I saw you starred my repo, but in case you need an example bot and you didn't see it, I have a bot class and a command class, put together into a chat bot that works well. The three files you'll need to read are [here](https://github.com/MitchellHarrison/mitchs-twitch-bot/blob/main/bot.py) for the bot class, [here](https://github.com/MitchellHarrison/mitchs-twitch-bot/blob/main/command.py) for the command class, and [here](https://github.com/MitchellHarrison/mitchs-twitch-bot/blob/main/chat_bot.py) for the chat bot script that I run to start it up. If you need credentials, you can check the [demo credentials file](https://github.com/MitchellHarrison/mitchs-twitch-bot/blob/main/credentials.env) to see where to put your credentials.
> 
> I hope this helps, and thanks for the star. ❤️
> 
> Also, feel free to ignore every other file. They're beyond the scope of your problem (luckily for you lol). Good luck!

Will did look in your repo good example bot so thank you
